include:
    # Metadata shared by many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml

    # OS builds
    - local: .gitlab/os-android.yml
    - local: .gitlab/os-ios.yml
    - local: .gitlab/release.yml


# NOTE: It’s possible to overwrite a globally defined before_script or after_script with per-job actions
# Deploy host gradle.properties to the root of the repo
# CI_GRADLE_PROPERTIES_PATH is set in runner config
default:
  before_script:
    - ""

stages:
    - Lint Javascript
    - Cut Release
    - Build
    # Add test stage when build system will be ready for it
    - Test Dist Sample Apps

############################################## pipeline jobs

build:android:device:release:
    stage: Build
    
    before_script:
        - cp -v $CI_GRADLE_PROPERTIES_PATH .
        - cp -rf -v $CI_REF_APP_GOOGLE_SERVICE_PATH ./android/app
        - cp -rf -v $CI_REF_APP_CONFIG_PATH ./android/app/src/main/assets
        
    extends:
        - .conf:android:env
        - .conf:android:release
        - .conf:android:artifacts
        - .conf:android:runner:tags
        - .conf:rule:default
        - .build:android:do
        
build:ios:device:release:
    stage: Build
    
    before_script:
        - ./scripts/ci_unlock_appledev_keychain.sh
        - cd ios/
        - pwd
    
    extends:
        - .conf:ios:runner:tags
        - .lint:ios:do
        - .build:ios:do

test:android:dist:samples:
    extends:
        - .conf:android:env
        - .conf:android:release
        - .conf:android:runner:tags
        - .conf:rule:default
        - .test:android:do

    dependencies:
        - build:android:device:release

lint:javascript:
    stage: Lint Javascript
    
    tags:
        - rtc-mac-docker
    
    image: node:16-slim

    script:
        - cd javascript
        - npm ci
        - npm run lint
