include:
  # Metadata shared by many jobs
  - local: .gitlab/rules.yml
  - local: .gitlab/artifacts.yml
  # OS builds
  - local: .gitlab/os-android.yml
  - local: .gitlab/os-ios.yml

# NOTE: It’s possible to overwrite a globally defined before_script or after_script with per-job actions
# Deploy host gradle.properties to the root of the repo
# CI_GRADLE_PROPERTIES_PATH is set in runner config
default:
  before_script:
    - ""

stages:
  - Lint Javascript
  - Cut Release
  - Build
  - Update SDK version

############################################## pipeline jobs

build:android:device:release:
  stage: Build
  before_script:
    - cp -v "$CI_REF_APP_GOOGLE_SERVICES_DEFAULT" ./android/app/google-services.json
    - cp -v "$CI_REF_APP_CONFIG_DEFAULT" ./android/app/src/main/assets/config.json

  extends:
    - .conf:android:env
    - .conf:android:release
    - .conf:android:artifacts
    - .conf:android:runner:tags
    - .conf:rule:default
    - .build:android:do

build:ios:device:release:
  stage: Build

  before_script:
    - ./scripts/ci_unlock_appledev_keychain.sh
    - cd ios/
    - pwd

  extends:
    - .conf:ios:runner:tags
    - .conf:rule:default
    - .lint:ios:do
    - .build:ios:do

lint:javascript:
  stage: Lint Javascript

  extends:
    - .conf:rule:default

  tags:
    - default

  image: node:16-slim

  script:
    - cd javascript
    - npm ci
    - npm run lint

# Multi project job

update:sdk:version:android:
  stage: Update SDK version
  extends:
    - .conf:android:runner:tags
    - .conf:rule:android:update:sdk
  script:
    - ./scripts/ci_update_android_version.sh $SDK_VERSION $SDK_REVISION
  needs:
    - project: sinch/sinch-projects/voice/vvc-client-sdk/android-sdk
      job: ${ARTIFACT_JOB_NAME}
      ref: ${PARENT_REF}
      artifacts: true

update:sdk:version:ios:
  stage: Update SDK version
  extends:
    - .conf:android:runner:tags # Reuse the same runner for iOS SDK update job as it doesn't require macOS specific features
    - .conf:rule:ios:update:sdk
  script:
    - ./scripts/ci_update_ios_version.sh "$SDK_VERSION%2b$SDK_REVISION"
  needs:
    - project: sinch/sinch-projects/voice/vvc-client-sdk/ios-sdk
      job: ${ARTIFACT_JOB_NAME}
      ref: ${PARENT_REF}
      artifacts: true
